[cmd_duration]
disabled = true

[directory]
style = "cyan"

[git_branch]
symbol = "ï˜ "
style = "bold dimmed purple"

[git_status]
conflicted = "ä·…"
ahead.value = "âŸ«"
ahead.style = "green"
behind.value = "âŸª"
behind.style = "red"
diverged = "ğŸ”€"
untracked.value = " â“â€"
untracked.style = "purple"
stashed = "â†ª"
modified.value = "â•"
modified.style = "yellow"
staged.value = "ğš« "
staged.style = "green"
format = '([\[$all_status$ahead_behind\]]($style) )'
renamed = "â‡†"
deleted.value = "âœ˜ "
deleted.style = "red"
style = "bold red"

[memory_usage]
symbol = "ï¡š "

[nix_shell]
symbol = "ï‹œ "
